name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - name: Build and push Dockerfile
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        builder: ${{ steps.buildx.outputs.name }}
        platforms: linux/amd64
        push: true
        tags: hdfeos/hdfeos:latest

